// TO SERVER
export const NEW_MESSAGE = 'NEW_MESSAGE';

export const STARTED_TYPING = 'STARTED_TYPING';

export const STOPPED_TYPING = 'STOPPED_TYPING';

// FROM SERVER
export const SET_USERS = 'SET_USERS';

export const ADD_MESSAGE = 'ADD_MESSAGE';

export const SET_CURRENT_WRITER = 'SET_CURRENT_WRITER';
